-- ⚠ NO-OP MIGRATION — DO NOT EXECUTE.
--
-- This migration was superseded before being applied.
-- The book feedback feature uses the existing feedback_books table
-- defined in 20260621_remaining_tables.sql (already applied).
--
-- History: an attempt to create book_feedback was made, then found
-- duplicate. Backend and admin CLI both use feedback_books.
-- This file is kept for audit trail only.
--
-- If you are running migrations from scratch, 20260621_remaining_tables.sql
-- already creates feedback_books with the correct schema and RLS policies.
-- No action needed here.
